CREATE TABLE USUARIOS (
id INT AUTO_INCREMENT PRIMARY KEY,
login VARCHAR(255) NOT NULL,
senha VARCHAR(255) NOT NULL,
);

CREATE TABLE UNI (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255)) NOT NULL,
);